/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import daoimpl.NhanVien_Daoimpl;
import javax.swing.JOptionPane;
import entity.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.security.SecureRandom;
import javax.swing.Icon;
import javax.swing.JButton;
import service.MailSender;
import util.XIcon;
import util.XJdbc;

/**
 *
 * @author Administrator
 */
public class frmDangNhap extends javax.swing.JFrame {

    private NhanVien_Daoimpl repoNV = new NhanVien_Daoimpl();

    private boolean showPassworld = false;

    /**
     * Creates new form frmLogin
     */
    public frmDangNhap() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDangNhap = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        btnQuenMatKhau = new javax.swing.JButton();
        lblShowPassworld = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");

        jPanel1.setBackground(new java.awt.Color(207, 231, 255));

        lblDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDangNhap.setForeground(new java.awt.Color(13, 71, 161));
        lblDangNhap.setText("Đăng nhập");

        lblTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(13, 71, 161));
        lblTaiKhoan.setText("Tài khoản");

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(13, 71, 161));
        lblMatKhau.setText("Mật khẩu");

        txtTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTaiKhoanKeyPressed(evt);
            }
        });

        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });

        btnDangNhap.setBackground(java.awt.Color.blue);
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login.png"))); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setPreferredSize(new java.awt.Dimension(116, 35));
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnQuenMatKhau.setBackground(java.awt.Color.blue);
        btnQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnQuenMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pass.png"))); // NOI18N
        btnQuenMatKhau.setText("Quên mật khẩu");
        btnQuenMatKhau.setPreferredSize(new java.awt.Dimension(140, 35));
        btnQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuenMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuenMatKhauMouseExited(evt);
            }
        });
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });

        lblShowPassworld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/An.png"))); // NOI18N
        lblShowPassworld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPassworldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDangNhap)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTaiKhoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMatKhau)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblShowPassworld)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblDangNhap)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTaiKhoan)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatKhau)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblShowPassworld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
        // TODO add your handling code here:
        String username = JOptionPane.showInputDialog(this, "Nhập mã nhân viên", "Quên mật khẩu", JOptionPane.INFORMATION_MESSAGE);

        if (username == null) {
            return;
        }
        if (username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã nhân viên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean found = false;
        NhanVien nhanVien = repoNV.findByMaNV(username);
        if (nhanVien == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã nhân viên trong hệ thống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (username.trim().equalsIgnoreCase(nhanVien.getMaNhanVien())) {
            found = true;
            String otpRandom = passwordRandom();
            MailSender.sendMailOTP(nhanVien.getEmail(), nhanVien.getHoVaTen(), nhanVien.getMaNhanVien(), otpRandom);
            int attempt = 0;
            while (attempt < 3) {
                String otpGet = JOptionPane.showInputDialog(this, "Nhập OTP nhận được từ email đăng ký!", "Quên mật khẩu", JOptionPane.INFORMATION_MESSAGE);
                if (otpGet == null) {
                    return;
                }
                if (otpGet.trim().equals(otpRandom)) {
                    String newPassword = passwordRandom();
                    repoNV.updatePassword(newPassword, nhanVien.getMaNhanVien());
                    MailSender.sendMailPassword(nhanVien.getEmail(), nhanVien.getHoVaTen(), nhanVien.getMaNhanVien(), newPassword);
                    JOptionPane.showMessageDialog(this, "Mật khẩu mới đã được gửi về email đăng ký của bạn!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                    return;
                } else {
                    attempt++;
                    if (attempt == 3) {
                        break;
                    }
                    JOptionPane.showMessageDialog(this, "OTP không đúng! Bạn còn " + (3 - attempt) + " lần thử.", "Sai OTP", JOptionPane.WARNING_MESSAGE);
                }
            }
            JOptionPane.showMessageDialog(this, "Bạn đã nhập sai OTP quá 3 lần. Vui lòng thử lại sau!", "Thất bại", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã nhân viên trong hệ thống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    private void txtTaiKhoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaiKhoanKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtMatKhau.requestFocus();
        }
    }//GEN-LAST:event_txtTaiKhoanKeyPressed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.btnDangNhapActionPerformed(null);
        }
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:

        boolean found = false;
        String taiKhoan = txtTaiKhoan.getText().trim();
        String matKhauNhap = new String(txtMatKhau.getPassword());

        if (taiKhoan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tài khoản", "Thông báo!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (matKhauNhap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu", "Thông báo!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        NhanVien nhanVien = repoNV.findByMaNV(taiKhoan);
        if (nhanVien == null) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (nhanVien.getMaNhanVien().trim().equalsIgnoreCase(taiKhoan) && nhanVien.getMatKhau().trim().equalsIgnoreCase(matKhauNhap)) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            frmTrangChu.nhanVienHienTai = nhanVien;
            new frmTrangChu().setVisible(true);
            this.dispose();
            found = true;
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblShowPassworldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPassworldMouseClicked
        // TODO add your handling code here:
        showPassworld = !showPassworld;
        if (showPassworld) {
            lblShowPassworld.setIcon(XIcon.getIcon("/icon/Hien.png"));
            txtMatKhau.setEchoChar((char) 0);
        } else {
            lblShowPassworld.setIcon(XIcon.getIcon("/icon/An.png"));
            txtMatKhau.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_lblShowPassworldMouseClicked

    private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
        // TODO add your handling code here:
        btnDangNhap.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnDangNhapMouseEntered

    private void btnDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseExited
        // TODO add your handling code here:
        btnDangNhap.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnDangNhapMouseExited

    private void btnQuenMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuenMatKhauMouseEntered
        // TODO add your handling code here:
        btnQuenMatKhau.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnQuenMatKhauMouseEntered

    private void btnQuenMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuenMatKhauMouseExited
        // TODO add your handling code here:
        btnQuenMatKhau.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnQuenMatKhauMouseExited

    public String passwordRandom() {
        String pass = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        SecureRandom sd = new SecureRandom();
        StringBuilder sb = new StringBuilder(6);
        for (int i = 0; i < 6; i++) {
            sb.append(pass.charAt(sd.nextInt(pass.length())));
        }
        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnQuenMatKhau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblShowPassworld;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

}
