/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import entity.NhanVien;
import java.awt.Panel;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class frmTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangChu
     */
    public static NhanVien nhanVienHienTai = new NhanVien(
            "hieu", "123456", "hieu",
            java.sql.Date.valueOf("2026-11-13"),
            true,
            "hhhhhhhhh", "hhhhhhhhhh", "hhhhhhhhh",
            1,
            "C:\\Users\\Administrator\\Pictures\\Screenshots\\9c492c3ca0127b4319ea94183a68681a.png",
            true
    );

    public frmTrangChu() {
        initComponents();
        setLocationRelativeTo(this);
        lblTenNguoiDung.setText(nhanVienHienTai.getHoVaTen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        btnTrangchu = new javax.swing.JButton();
        btnKhachhang = new javax.swing.JButton();
        btnNhanvien = new javax.swing.JButton();
        btnKhuyenmai = new javax.swing.JButton();
        btnSanpham = new javax.swing.JButton();
        btnBanhang = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        btnHoadon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lblTenNguoiDung = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        jpMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");

        jPanel2.setBackground(new java.awt.Color(187, 222, 251));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnTrangchu.setBackground(java.awt.Color.blue);
        btnTrangchu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        btnTrangchu.setText("Trang chủ ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 23);
        jPanel2.add(btnTrangchu, gridBagConstraints);

        btnKhachhang.setBackground(java.awt.Color.blue);
        btnKhachhang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconKH.png"))); // NOI18N
        btnKhachhang.setText("Khách hàng ");
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 41, 0, 23);
        jPanel2.add(btnKhachhang, gridBagConstraints);

        btnNhanvien.setBackground(java.awt.Color.blue);
        btnNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconNV.png"))); // NOI18N
        btnNhanvien.setText("Nhân viên ");
        btnNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanvienActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 41, 0, 23);
        jPanel2.add(btnNhanvien, gridBagConstraints);

        btnKhuyenmai.setBackground(java.awt.Color.blue);
        btnKhuyenmai.setForeground(new java.awt.Color(255, 255, 255));
        btnKhuyenmai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/coupon (1).png"))); // NOI18N
        btnKhuyenmai.setText("Khuyến mại ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 41, 0, 23);
        jPanel2.add(btnKhuyenmai, gridBagConstraints);

        btnSanpham.setBackground(java.awt.Color.blue);
        btnSanpham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/box.png"))); // NOI18N
        btnSanpham.setText("Sản phẩm");
        btnSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanphamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 41, 0, 23);
        jPanel2.add(btnSanpham, gridBagConstraints);

        btnBanhang.setBackground(java.awt.Color.blue);
        btnBanhang.setForeground(new java.awt.Color(255, 255, 255));
        btnBanhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconBanHang.png"))); // NOI18N
        btnBanhang.setText("Bán hàng ");
        btnBanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanhangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 41, 0, 23);
        jPanel2.add(btnBanhang, gridBagConstraints);

        btnThongke.setBackground(java.awt.Color.blue);
        btnThongke.setForeground(new java.awt.Color(255, 255, 255));
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Best.png"))); // NOI18N
        btnThongke.setText("Thống kê ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 41, 0, 23);
        jPanel2.add(btnThongke, gridBagConstraints);

        btnHoadon.setBackground(java.awt.Color.blue);
        btnHoadon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Properties.png"))); // NOI18N
        btnHoadon.setText("Hóa đơn ");
        btnHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoadonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 41, 0, 23);
        jPanel2.add(btnHoadon, gridBagConstraints);

        btnThoat.setBackground(java.awt.Color.blue);
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Closed door.png"))); // NOI18N
        btnThoat.setText("Thoát");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 41, 24, 23);
        jPanel2.add(btnThoat, gridBagConstraints);

        lblTenNguoiDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNguoiDung.setForeground(new java.awt.Color(13, 71, 161));
        lblTenNguoiDung.setText("Nguyễn Ngọc Hiếu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 41, 0, 0);
        jPanel2.add(lblTenNguoiDung, gridBagConstraints);

        lblAnh.setForeground(new java.awt.Color(13, 71, 161));
        lblAnh.setText("Ảnh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.ipady = 121;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 35, 0, 0);
        jPanel2.add(lblAnh, gridBagConstraints);

        jpMain.setBackground(new java.awt.Color(207, 231, 255));
        jpMain.setPreferredSize(new java.awt.Dimension(1280, 720));
        jpMain.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                    .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setPanel(JPanel panel) {
        jpMain.removeAll();
        jpMain.add(panel);
        jpMain.revalidate(); 
        jpMain.repaint();
    }

    private void btnNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanvienActionPerformed
        // TODO add your handling code here:
        this.setPanel(new jpNhanVien());
    }//GEN-LAST:event_btnNhanvienActionPerformed

    private void btnSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanphamActionPerformed
        // TODO add your handling code here:
        this.setPanel(new jpSanPham());
    }//GEN-LAST:event_btnSanphamActionPerformed

    private void btnBanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanhangActionPerformed
        // TODO add your handling code here:
        this.setPanel(new jpBanHang());
    }//GEN-LAST:event_btnBanhangActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        // TODO add your handling code here:
        this.setPanel(new jpKhachHang());
    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void btnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoadonActionPerformed
        // TODO add your handling code here:
        this.setPanel(new jpHoaDon());
    }//GEN-LAST:event_btnHoadonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanhang;
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnKhuyenmai;
    private javax.swing.JButton btnNhanvien;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btnTrangchu;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpMain;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblTenNguoiDung;
    // End of variables declaration//GEN-END:variables
}
