/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import controller.Controller_BanHang;
import daoimpl.*;
import entity.HoaDon;
import entity.HoaDonChiTiet;
import entity.KhachHang;
import entity.KhuyenMai;
import entity.SanPham;
import java.awt.Color;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import service.HoaDonPDF;

/**
 *
 * @author Administrator
 */
public class jpBanHang extends javax.swing.JPanel implements Controller_BanHang {

    /**
     * Creates new form jpBanHang
     */
    private DefaultTableModel modelSP = new DefaultTableModel();
    private SanPham_Daoimpl repoSP = new SanPham_Daoimpl();
    private DefaultTableModel modelHD = new DefaultTableModel();
    private HoaDon_Daoimpl repoHD = new HoaDon_Daoimpl();
    private DefaultTableModel modelHDCT = new DefaultTableModel();
    private HoaDonChiTiet_Daoimpl repoHDCT = new HoaDonChiTiet_Daoimpl();
    private KhachHang_Daoimpl repoKH = new KhachHang_Daoimpl();
    private KhuyenMai_Daoimpl repoKM = new KhuyenMai_Daoimpl();

    public jpBanHang() {
        initComponents();
        txtNhanVien.setText(frmTrangChu.nhanVienHienTai.getMaNhanVien());
        this.fillToTable();
        this.fillToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpuThem = new javax.swing.JPopupMenu();
        iThem = new javax.swing.JMenuItem();
        iXoa = new javax.swing.JMenuItem();
        jpuGoiY = new javax.swing.JPopupMenu();
        jpHoaDon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jpGioHang = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jpSanPham = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jpDonHang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblTienKhachDua = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        txtMaHD = new javax.swing.JTextField();
        txtEmailKH = new javax.swing.JTextField();
        txtSDTKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        cboThanhToan = new javax.swing.JComboBox<>();
        cboVoucher = new javax.swing.JComboBox<>();
        txtTienThua = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnTaoDon = new javax.swing.JButton();
        btnHuyDon = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        cbGuiHoaDon = new javax.swing.JCheckBox();

        iThem.setText("Thêm vào giỏ hàng");
        iThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iThemActionPerformed(evt);
            }
        });
        jpuThem.add(iThem);

        iXoa.setText("Xóa khỏi giỏ hàng");
        iXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iXoaActionPerformed(evt);
            }
        });
        jpuThem.add(iXoa);

        jpuGoiY.setFocusable(false);

        setBackground(new java.awt.Color(207, 231, 255));
        setForeground(new java.awt.Color(13, 71, 161));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jpHoaDon.setBackground(new java.awt.Color(207, 231, 255));
        jpHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách đơn hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(30, 136, 229))); // NOI18N
        jpHoaDon.setPreferredSize(new java.awt.Dimension(640, 240));

        jScrollPane1.setBackground(new java.awt.Color(207, 231, 255));

        tblHoaDon.setBackground(new java.awt.Color(207, 231, 255));
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Tên KH", "Trạng thái", "Ngày tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setRowHeight(25);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jpHoaDonLayout = new javax.swing.GroupLayout(jpHoaDon);
        jpHoaDon.setLayout(jpHoaDonLayout);
        jpHoaDonLayout.setHorizontalGroup(
            jpHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpHoaDonLayout.setVerticalGroup(
            jpHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHoaDonLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpGioHang.setBackground(new java.awt.Color(207, 231, 255));
        jpGioHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(30, 136, 229))); // NOI18N
        jpGioHang.setPreferredSize(new java.awt.Dimension(640, 240));

        tblGioHang.setBackground(new java.awt.Color(207, 231, 255));
        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID SP", "Tên sản phẩm", "Số lượng", "Đơn giá", "Giảm giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.setRowHeight(25);
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGioHang);

        javax.swing.GroupLayout jpGioHangLayout = new javax.swing.GroupLayout(jpGioHang);
        jpGioHang.setLayout(jpGioHangLayout);
        jpGioHangLayout.setHorizontalGroup(
            jpGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGioHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpGioHangLayout.setVerticalGroup(
            jpGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGioHangLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpSanPham.setBackground(new java.awt.Color(207, 231, 255));
        jpSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(30, 136, 229))); // NOI18N
        jpSanPham.setPreferredSize(new java.awt.Dimension(640, 240));

        tblSanPham.setBackground(new java.awt.Color(207, 231, 255));
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên SP", "Màu", "Loại", "Chất liệu", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setRowHeight(25);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPham);

        javax.swing.GroupLayout jpSanPhamLayout = new javax.swing.GroupLayout(jpSanPham);
        jpSanPham.setLayout(jpSanPhamLayout);
        jpSanPhamLayout.setHorizontalGroup(
            jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpSanPhamLayout.setVerticalGroup(
            jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSanPhamLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpDonHang.setBackground(new java.awt.Color(207, 231, 255));
        jpDonHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(30, 136, 229))); // NOI18N

        jLabel1.setText("Tên KH");

        jLabel2.setText("SDT");

        jLabel3.setText("Email");

        jLabel4.setText("Mã HD");

        jLabel5.setText("Thanh toán");

        lblTongTien.setText("Tổng tiền");

        lblTienKhachDua.setText("Tiền khách đưa");

        lblTienThua.setText("Tiền thừa");

        jLabel9.setText("Voucher");

        jLabel10.setText("Giảm giá");

        jLabel11.setText("Nhân viên");

        jLabel12.setText("Ghi chú");

        txtTienKhachDua.setPreferredSize(new java.awt.Dimension(200, 25));
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        txtTongTien.setFocusable(false);
        txtTongTien.setPreferredSize(new java.awt.Dimension(200, 25));

        txtMaHD.setFocusable(false);
        txtMaHD.setPreferredSize(new java.awt.Dimension(200, 25));

        txtEmailKH.setPreferredSize(new java.awt.Dimension(200, 25));

        txtSDTKH.setPreferredSize(new java.awt.Dimension(200, 25));
        txtSDTKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKHKeyReleased(evt);
            }
        });

        txtTenKH.setToolTipText("");
        txtTenKH.setPreferredSize(new java.awt.Dimension(200, 25));

        cboThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản" }));
        cboThanhToan.setPreferredSize(new java.awt.Dimension(200, 25));
        cboThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThanhToanActionPerformed(evt);
            }
        });

        cboVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không dùng" }));
        cboVoucher.setPreferredSize(new java.awt.Dimension(200, 25));
        cboVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVoucherActionPerformed(evt);
            }
        });

        txtTienThua.setFocusable(false);
        txtTienThua.setPreferredSize(new java.awt.Dimension(200, 25));

        txtGiamGia.setFocusable(false);
        txtGiamGia.setPreferredSize(new java.awt.Dimension(200, 25));

        txtNhanVien.setFocusable(false);
        txtNhanVien.setPreferredSize(new java.awt.Dimension(200, 25));

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane4.setViewportView(txtGhiChu);

        btnTaoDon.setBackground(java.awt.Color.blue);
        btnTaoDon.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Create.png"))); // NOI18N
        btnTaoDon.setText("Tạo đơn");
        btnTaoDon.setPreferredSize(new java.awt.Dimension(74, 35));
        btnTaoDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaoDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaoDonMouseExited(evt);
            }
        });
        btnTaoDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoDonActionPerformed(evt);
            }
        });

        btnHuyDon.setBackground(java.awt.Color.blue);
        btnHuyDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnHuyDon.setText("Hủy đơn");
        btnHuyDon.setPreferredSize(new java.awt.Dimension(91, 35));
        btnHuyDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHuyDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHuyDonMouseExited(evt);
            }
        });
        btnHuyDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDonActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(java.awt.Color.blue);
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setPreferredSize(new java.awt.Dimension(91, 35));
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseExited(evt);
            }
        });
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        cbGuiHoaDon.setText("Gửi hóa đơn cho khách hàng");
        cbGuiHoaDon.setPreferredSize(new java.awt.Dimension(84, 25));
        cbGuiHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGuiHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDonHangLayout = new javax.swing.GroupLayout(jpDonHang);
        jpDonHang.setLayout(jpDonHangLayout);
        jpDonHangLayout.setHorizontalGroup(
            jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaoDon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongTien)
                    .addComponent(lblTienKhachDua)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(lblTienThua)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDonHangLayout.createSequentialGroup()
                        .addComponent(btnHuyDon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbGuiHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTienThua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboVoucher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboThanhToan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSDTKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jpDonHangLayout.setVerticalGroup(
            jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDonHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmailKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbGuiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jpDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jpDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jpDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoDonActionPerformed
        // TODO add your handling code here:
        if (txtTenKH.getText().isEmpty() || txtSDTKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập tông tin khách hàng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        this.create();
        this.fillToTable();
        fillToTableFind();
    }//GEN-LAST:event_btnTaoDonActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tblSanPham.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            tblSanPham.setRowSelectionInterval(row, row);
        }
        if (evt.getButton() == MouseEvent.BUTTON3) {
            iThem.setVisible(true);
            iXoa.setVisible(false);
            jpuThem.show(tblSanPham, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void iThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iThemActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 0).toString());
        SanPham sanPham = repoSP.findById(id);
        HoaDonChiTiet HDCT = new HoaDonChiTiet();
        HoaDon hd = repoHD.findByMaHD(txtMaHD.getText());
        if (hd == null) {
            JOptionPane.showMessageDialog(this, "Chưa chọn hóa đơn nào!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idHD = hd.getId();
        HDCT.setMaHoaDon(txtMaHD.getText());
        HDCT.setIdHoaDon(idHD);
        HDCT.setIdSanPham(sanPham.getId());
        String inputSL = JOptionPane.showInputDialog("Nhập số lượng");
        if (inputSL.isEmpty()) {
            return;
        }
        int soLuong;
        try {
            soLuong = Integer.parseInt(inputSL);
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");
                return;
            }
            if (soLuong > sanPham.getSoLuong()) {
                JOptionPane.showMessageDialog(this, "Số lượng vượt quá tồn kho! \nTồn kho hiện tại: " + sanPham.getSoLuong());
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ, vui lòng nhập số!");
            return;
        }
        HDCT.setSoLuong(soLuong);
        HDCT.setDonGia(sanPham.getDonGia());
        boolean check = false;
        for (HoaDonChiTiet hoaDonChiTiet : repoHDCT.findByMaHDList(txtMaHD.getText())) {
            if (hoaDonChiTiet.getIdSanPham() == HDCT.getIdSanPham()) {
                hoaDonChiTiet.setSoLuong(hoaDonChiTiet.getSoLuong() + soLuong);
                repoHDCT.updateSL(hoaDonChiTiet);
                repoSP.updateSoLuong((sanPham.getSoLuong() - soLuong), hoaDonChiTiet.getIdSanPham());
                check = true;
                break;
            }
        }
        if (!check) {
            repoHDCT.create(HDCT);
            repoSP.updateSoLuong((sanPham.getSoLuong() - soLuong), HDCT.getIdSanPham());
        }
        this.fillToTable();
        fillToTableFind();
        this.updateTongTien();
        cboVoucherActionPerformed(null);
    }//GEN-LAST:event_iThemActionPerformed
    private String formatMoney(BigDecimal money) {
        if (money == null) {
            return "";
        }
        DecimalFormat df = new DecimalFormat("#,### VNĐ");
        return df.format(money);
    }

    private BigDecimal parseMoney(String text) {
        if (text == null || text.trim().isEmpty()) {
            return BigDecimal.ZERO;
        }
        try {
            String cleaned = text.replace("VNĐ", "").replace(",", "").trim();
            return new BigDecimal(cleaned);
        } catch (Exception e) {
            e.printStackTrace();
            return BigDecimal.ZERO;
        }
    }

    private void updateTongTien() {
        BigDecimal tongTien = BigDecimal.ZERO;

        for (int i = 0; i < modelHDCT.getRowCount(); i++) {
            Object value = modelHDCT.getValueAt(i, 5);

            if (value != null) {
                BigDecimal thanhTien = parseMoney(value.toString());
                tongTien = tongTien.add(thanhTien);
            }
        }
        txtTongTien.setText(formatMoney(tongTien));
    }
    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        txtTenKH.setText(tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 1).toString());
        KhachHang kh = new KhachHang();
        for (HoaDon hoaDon : repoHD.findAll()) {
            if (hoaDon.getTrangThai() == 0) {
                if (hoaDon.getMaHoaDon().equals(tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 0))) {
                    txtMaHD.setText(hoaDon.getMaHoaDon());
                    txtGhiChu.setText(hoaDon.getGhiChu());
                    kh = repoKH.findById(hoaDon.getIdKhachHang());
                    System.out.println("id KM: " + hoaDon.getIdKhuyenMai());
                    if (hoaDon.getIdKhuyenMai() != null) {
                        cboVoucher.setSelectedItem(repoKM.findById(hoaDon.getIdKhuyenMai()).getTenKM());
                    } else if (hoaDon.getIdKhuyenMai() == null) {
                        cboVoucher.setSelectedIndex(0);
                    }
                    break;
                }
            }
        }
        txtSDTKH.setText(kh.getsDT());
        txtEmailKH.setText(kh.getEmail());
        fillToTableFind();
        this.updateTongTien();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        // TODO add your handling code here:
        if (txtTongTien.getText().trim().isEmpty()) {
            return;
        }
        if (txtTienKhachDua.getText().trim().isEmpty()) {
            txtTienThua.setText("");
            return;
        }
        txtTienThua.setText(formatMoney(parseMoney(txtTienKhachDua.getText()).subtract(parseMoney(txtTongTien.getText()))));
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void btnHuyDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDonActionPerformed
        // TODO add your handling code here:
        if (txtMaHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn nào!\nVui lòng hóa đơn cần hủy!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int kt = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn hủy hóa đơn này không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kt == 0) {
            String lyDoHuyDon = JOptionPane.showInputDialog("Nhập lý do hủy đơn!");
            for (int i = 0; i < tblGioHang.getRowCount(); i++) {
                SanPham sanPham = repoSP.findById(Integer.parseInt(tblGioHang.getValueAt(i, 0).toString()));
                repoSP.updateSoLuong((sanPham.getSoLuong() + Integer.parseInt(tblGioHang.getValueAt(i, 2).toString())), Integer.parseInt(tblGioHang.getValueAt(i, 0).toString()));
            }
            repoHD.updateHuyDon(new HoaDon(txtMaHD.getText(), parseMoney(txtTongTien.getText()), -1, lyDoHuyDon));
            this.clear();
            this.fillToTable();
            fillToTableFind();
            JOptionPane.showMessageDialog(this, "Hủy đơn thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnHuyDonActionPerformed
    public String maHoaDonRandom() {
        String chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        SecureRandom random = new SecureRandom();
        StringBuilder sb = new StringBuilder(6);

        for (int i = 0; i < 6; i++) {
            sb.append(chars.charAt(random.nextInt(chars.length())));
        }

        return "HD" + sb.toString();
    }

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        if (txtMaHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn nào!\nVui lòng hóa đơn cần thanh toán!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (tblGioHang.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Giỏ hàng của bạn chưa có món đồ nào!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cbGuiHoaDon.isSelected() && txtEmailKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email để nhận hóa đơn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtEmailKH.requestFocus();
            return;
        }

        if (cboThanhToan.getSelectedIndex() == 0) {
            if (txtTienKhachDua.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tiền khách đưa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                txtTienKhachDua.requestFocus();
                return;
            }
            if (parseMoney(txtTongTien.getText()).compareTo(parseMoney(txtTienKhachDua.getText())) >= 0) {
                JOptionPane.showMessageDialog(this, "Khách chưa đưa đủ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                txtTienKhachDua.requestFocus();
                return;
            }
        }
        int kt = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thanh toán không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kt == 0) {
            int idPGG = repoKM.findBytenKM(cboVoucher.getSelectedItem().toString()).getId();
            if (cboThanhToan.getSelectedIndex() == 0) {
                HoaDon hoaDon = new HoaDon(txtMaHD.getText(), parseMoney(txtTongTien.getText()), LocalDateTime.now(), parseMoney(txtTienKhachDua.getText()), parseMoney(txtTienThua.getText()), cboThanhToan.getSelectedItem().toString(), 1, idPGG, txtGhiChu.getText());
                repoHD.update(hoaDon);

            }
            if (cboThanhToan.getSelectedIndex() == 1) {
                jdGetQRThanhToan qr = new jdGetQRThanhToan((JFrame) SwingUtilities.getWindowAncestor(this), parseMoney(txtTongTien.getText()).toString(), txtMaHD.getText());
                qr.setVisible(true);
                if (jdGetQRThanhToan.result == 1) {
                    HoaDon hoaDon = new HoaDon(txtMaHD.getText(), parseMoney(txtTongTien.getText()), LocalDateTime.now(), cboThanhToan.getSelectedItem().toString(), 1, idPGG, txtGhiChu.getText());
                    repoHD.updateCK(hoaDon);
                }
            }
            if (jdGetQRThanhToan.result == 1) {
                String filePath = null;
                JOptionPane.showMessageDialog(this, "Thanh toán thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                FileDialog fd = new FileDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Chọn thư mục cần lưu", FileDialog.SAVE);
                fd.setDirectory("resources/hoadon");
                fd.setFile(txtMaHD.getText() + ".pdf");
                fd.setVisible(true);
                while (fd.getFile() == null) {
                    fd.setDirectory("resources/hoadon");
                    fd.setFile(txtMaHD.getText() + ".pdf");
                    fd.setVisible(true);
                }
                if (fd.getFile() != null) {
                    File file = new File(fd.getDirectory(), fd.getFile());
                    filePath = file.getPath();
                }
                HoaDon hd = repoHD.findByMaHD(txtMaHD.getText());
                KhachHang kh = repoKH.findByPhone(txtSDTKH.getText());
                List<HoaDonChiTiet> hoaDonChiTiet = repoHDCT.findByMaHDList(txtMaHD.getText());
                HoaDonPDF.exportPDF(hd, hoaDonChiTiet, kh, filePath);
                this.clear();
                this.fillToTable();
                fillToTableFind();
            } else {
                JOptionPane.showMessageDialog(this, "Đã hủy thanh toán!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cboVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVoucherActionPerformed
        // TODO add your handling code here:
        if (!txtMaHD.getText().isEmpty()) {
            int idHD = repoHD.findByMaHD(txtMaHD.getText()).getId();
            int phanTram = 0;
            KhuyenMai km = null;
            if (cboVoucher.getSelectedIndex() > 0) {
                km = repoKM.findBytenKM(cboVoucher.getSelectedItem().toString());
                if (km == null) {
                    System.out.println("Không tìm thấy khuyến mãi!");
                    return;
                }
                phanTram = km.getPhanTramGiam();
            }
            int idLoaiCuaPhieu = (km != null) ? km.getIdLoai() : -999;
            BigDecimal tongGiam = BigDecimal.ZERO;
            for (HoaDonChiTiet hdct : repoHDCT.findByIdList(idHD)) {
                BigDecimal tongGia = hdct.getDonGia().multiply(BigDecimal.valueOf(hdct.getSoLuong()));
                BigDecimal giamGia = BigDecimal.ZERO;
                if (phanTram > 0) {
                    int idLoaiSP = repoSP.findById(hdct.getIdSanPham()).getIdLoaiGiay();
                    if (idLoaiCuaPhieu == -1 || idLoaiCuaPhieu == idLoaiSP) {
                        giamGia = tongGia.multiply(BigDecimal.valueOf(phanTram)).divide(BigDecimal.valueOf(100));
                    } else {
                        giamGia = BigDecimal.ZERO;
                    }
                }
                tongGiam = tongGiam.add(giamGia);
                hdct.setGiamGia(giamGia);
                hdct.setThanhTien(tongGia.subtract(giamGia));
                repoHDCT.update(hdct);
            }
            txtGiamGia.setText(formatMoney(tongGiam));
            HoaDon hoaDon = new HoaDon();
            hoaDon.setMaHoaDon(txtMaHD.getText());
            if (km != null) {
                hoaDon.setIdKhuyenMai(km.getId());
            } else {
                hoaDon.setIdKhuyenMai(null);
            }
            repoHD.updateKhuyenMai(hoaDon);
            fillToTable();
            fillToTableFind();
            updateTongTien();
        }
    }//GEN-LAST:event_cboVoucherActionPerformed

    private void cbGuiHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGuiHoaDonActionPerformed
        // TODO add your handling code here:
        if (cbGuiHoaDon.isSelected() && txtEmailKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email để nhận hóa đơn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtEmailKH.requestFocus();
        }
    }//GEN-LAST:event_cbGuiHoaDonActionPerformed

    private void cboThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThanhToanActionPerformed
        // TODO add your handling code here:
        if (cboThanhToan.getSelectedIndex() == 0) {
            lblTienKhachDua.setVisible(true);
            lblTienThua.setVisible(true);
            txtTienThua.setVisible(true);
            txtTienKhachDua.setVisible(true);
        } else if (cboThanhToan.getSelectedIndex() == 1) {
            lblTienKhachDua.setVisible(false);
            lblTienThua.setVisible(false);
            txtTienThua.setVisible(false);
            txtTienKhachDua.setVisible(false);
        }
    }//GEN-LAST:event_cboThanhToanActionPerformed

    private void btnTaoDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoDonMouseEntered
        // TODO add your handling code here:
        btnTaoDon.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnTaoDonMouseEntered

    private void btnTaoDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoDonMouseExited
        // TODO add your handling code here:
        btnTaoDon.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnTaoDonMouseExited

    private void btnHuyDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyDonMouseEntered
        // TODO add your handling code here:
        btnHuyDon.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnHuyDonMouseEntered

    private void btnHuyDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyDonMouseExited
        // TODO add your handling code here:
        btnHuyDon.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnHuyDonMouseExited

    private void btnThanhToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseExited
        // TODO add your handling code here:
        btnThanhToan.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnThanhToanMouseExited

    private void btnThanhToanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseEntered
        // TODO add your handling code here:
        btnThanhToan.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnThanhToanMouseEntered

    private void txtSDTKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKHKeyReleased
        // TODO add your handling code here:
        jpuGoiY.setVisible(false);
        jpuGoiY.removeAll();
        for (KhachHang khachhang : repoKH.findListByPhone('%' + txtSDTKH.getText() + '%')) {
            JMenuItem item = new JMenuItem(khachhang.getsDT());
            item.addActionListener(e -> {
                txtTenKH.setText(khachhang.getHoVaTen());
                txtEmailKH.setText(khachhang.getEmail());
                txtSDTKH.setText(khachhang.getsDT());
                jpuGoiY.setVisible(false);
            });
            jpuGoiY.add(item);
        }
        jpuGoiY.show(txtSDTKH, txtSDTKH.getWidth(), txtSDTKH.getHeight() + 25);
    }//GEN-LAST:event_txtSDTKHKeyReleased

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
        int row = tblGioHang.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            tblGioHang.setRowSelectionInterval(row, row);
        }
        if (evt.getButton() == MouseEvent.BUTTON3) {
            iThem.setVisible(false);
            iXoa.setVisible(true);
            jpuThem.show(tblGioHang, evt.getX(), evt.getY());
        }
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int idSP = Integer.parseInt(tblGioHang.getValueAt(tblGioHang.getSelectedRow(), 0).toString());
            SanPham sanPham = repoSP.findById(idSP);
            if (tblGioHang.getSelectedColumn() == 2) {
                String inputSL = JOptionPane.showInputDialog("Nhập số lượng");
                if (inputSL == null || inputSL.trim().isEmpty()) {
                    return;
                }
                int soLuong;
                try {
                    soLuong = Integer.parseInt(inputSL);
                    if (soLuong <= 0) {
                        JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");
                        return;
                    }
                    if (soLuong > sanPham.getSoLuong()) {
                        JOptionPane.showMessageDialog(this, "Số lượng vượt quá tồn kho! \nTồn kho hiện tại: " + sanPham.getSoLuong());
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ, vui lòng nhập số!");
                    return;
                }
                HoaDonChiTiet hoaDonChiTiet = new HoaDonChiTiet();
                hoaDonChiTiet.setMaHoaDon(txtMaHD.getText());
                hoaDonChiTiet.setIdSanPham(idSP);
                hoaDonChiTiet.setSoLuong(soLuong);
                repoHDCT.updateSL(hoaDonChiTiet);
                fillToTable();
                fillToTableFind();
                this.updateTongTien();
                cboVoucherActionPerformed(null);
            }
        }
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void iXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iXoaActionPerformed
        // TODO add your handling code here:
        int idSP = Integer.parseInt(tblGioHang.getValueAt(tblGioHang.getSelectedRow(), 0).toString());
        int tongSoLuong = repoSP.findById(idSP).getSoLuong();
        int soLuongXoa = Integer.parseInt(tblGioHang.getValueAt(tblGioHang.getSelectedRow(), 2).toString());
        repoHDCT.deleteByIdSP(idSP, txtMaHD.getText());
        repoSP.updateSoLuong((tongSoLuong + soLuongXoa), idSP);
        fillToTable();
        this.updateTongTien();
        cboVoucherActionPerformed(null);
    }//GEN-LAST:event_iXoaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyDon;
    private javax.swing.JButton btnTaoDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JCheckBox cbGuiHoaDon;
    private javax.swing.JComboBox<String> cboThanhToan;
    private javax.swing.JComboBox<String> cboVoucher;
    private javax.swing.JMenuItem iThem;
    private javax.swing.JMenuItem iXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpDonHang;
    private javax.swing.JPanel jpGioHang;
    private javax.swing.JPanel jpHoaDon;
    private javax.swing.JPanel jpSanPham;
    private javax.swing.JPopupMenu jpuGoiY;
    private javax.swing.JPopupMenu jpuThem;
    private javax.swing.JLabel lblTienKhachDua;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtEmailKH;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtSDTKH;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(HoaDon entity) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public HoaDon getForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToTable() {
        modelSP = (DefaultTableModel) tblSanPham.getModel();
        modelSP.setRowCount(0);
        for (SanPham sanPham : repoSP.findAll()) {
            modelSP.addRow(new Object[]{sanPham.getId(), sanPham.getTenGiay(), sanPham.getTenMau(), sanPham.getTenLoai(), sanPham.getTenChatLieu(), sanPham.getSoLuong(), formatMoney(sanPham.getDonGia())});
        }
        modelHD = (DefaultTableModel) tblHoaDon.getModel();
        modelHD.setRowCount(0);
        for (HoaDon hoaDon : repoHD.findAll()) {
            if (hoaDon.getTrangThai() == 0) {
                String trangThai = switch (hoaDon.getTrangThai()) {
                    case -1 ->
                        "Đã hủy";
                    case 0 ->
                        "Chưa thanh toán";
                    case 1 ->
                        "Đã thanh toán";
                    default ->
                        "Không xác định";
                };
                modelHD.addRow(new Object[]{hoaDon.getMaHoaDon(), hoaDon.getHoVaTen(), trangThai, hoaDon.getNgayTao().format(DateTimeFormatter.ofPattern("HH:mm dd/MM/yyyy"))});
            }
        }

    }

    @Override
    public void fillToTableFind() {
        modelHDCT = (DefaultTableModel) tblGioHang.getModel();
        modelHDCT.setRowCount(0);
        if (!txtMaHD.getText().isEmpty()) {
            int idHD = repoHD.findByMaHD(txtMaHD.getText()).getId();
            for (HoaDonChiTiet hoaDonChiTiet : repoHDCT.findAll()) {
                if (hoaDonChiTiet.getIdHoaDon() == idHD) {
                    String tenSp = repoSP.findById(hoaDonChiTiet.getIdSanPham()).getTenGiay();
                    modelHDCT.addRow(new Object[]{hoaDonChiTiet.getIdSanPham(), tenSp, hoaDonChiTiet.getSoLuong(), formatMoney(hoaDonChiTiet.getDonGia()), formatMoney(hoaDonChiTiet.getGiamGia()), formatMoney(hoaDonChiTiet.getThanhTien())});
                }
            }
        }
    }

    @Override
    public void fillToComboBox() {
        cboVoucher.removeAllItems();
        cboVoucher.addItem("Không dùng");
        for (KhuyenMai khuyenMai : repoKM.findAll()) {
            if (khuyenMai.getNgayKetThuc().isAfter(LocalDateTime.now()) && khuyenMai.isTrangThai()) {
                cboVoucher.addItem(khuyenMai.getTenKM());
            }
        }
    }

    @Override
    public void edit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void create() {
        int idkh = repoKH.getOrCreateCustomer(txtTenKH.getText(), txtSDTKH.getText(), txtEmailKH.getText());
        String uid = maHoaDonRandom();
        while (repoHD.findByMaHD(uid.toString()) != null) {
            uid = maHoaDonRandom();
        }
        txtMaHD.setText(uid.toString());
        HoaDon hoadon = new HoaDon();
        hoadon.setMaHoaDon(uid.toString());
        hoadon.setIdKhachHang(idkh);
        hoadon.setMaNhanVien(frmTrangChu.nhanVienHienTai.getMaNhanVien());
        hoadon.setIdKhuyenMai(idkh);
        hoadon.setNgayTao(LocalDateTime.now());
        hoadon.setGhiChu(txtGhiChu.getText());
        repoHD.create(hoadon);

    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void delete() {
        int idHD = repoHD.findByMaHD(txtMaHD.getText()).getId();
        repoHDCT.deleteByIdHoaDon(idHD);
        repoHD.deleteById(idHD);
    }

    @Override
    public void clear() {
        txtTenKH.setText(null);
        txtSDTKH.setText(null);
        txtEmailKH.setText(null);
        txtMaHD.setText(null);
        cboThanhToan.setSelectedIndex(0);
        txtTongTien.setText(null);
        txtTienKhachDua.setText(null);
        txtTienThua.setText(null);
        cboVoucher.setSelectedIndex(0);
        txtGiamGia.setText(null);
        txtGhiChu.setText(null);
        cbGuiHoaDon.setSelected(false);
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
