/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import daoimpl.*;
import entity.ChucVu;
import entity.NhanVien;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import controller.Controller_NhanVien;
import java.awt.FileDialog;
import java.awt.Frame;
import java.util.Date;

/**
 *
 * @author Administrator
 */
public class jpNhanVien extends javax.swing.JPanel implements Controller_NhanVien {

    /**
     * Creates new form jpNhanVien
     */
    private NhanVien_Daoimpl repoNV = new NhanVien_Daoimpl();
    private ChucVu_Daoimpl repoCV = new ChucVu_Daoimpl();
    private DefaultTableModel modelNV = new DefaultTableModel();
    private DefaultTableModel modelCV = new DefaultTableModel();
    private String fileAnh = "";

    public jpNhanVien() {
        initComponents();
        this.cboChucVuTimKiem.setVisible(false);
        this.setTableColumnWidths();
        this.fillToTable();
        this.fillToComboBox();
    }

    public void setTableColumnWidths() {
        tblNhanVien.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblNhanVien.getColumnModel().getColumn(1).setPreferredWidth(20);
        tblNhanVien.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblNhanVien.getColumnModel().getColumn(3).setPreferredWidth(20);
        tblNhanVien.getColumnModel().getColumn(4).setPreferredWidth(35);
        tblNhanVien.getColumnModel().getColumn(5).setPreferredWidth(35);
        tblNhanVien.getColumnModel().getColumn(9).setPreferredWidth(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSex = new javax.swing.ButtonGroup();
        btgTrangThai = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpNhanVien = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        lblHoVaTen = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lblAnhNV = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        lblGioiTinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoNghiLam = new javax.swing.JRadioButton();
        rdoDiLam = new javax.swing.JRadioButton();
        lblTrangThai = new javax.swing.JLabel();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        txtMatKhau = new javax.swing.JPasswordField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        cboTimKiem = new javax.swing.JComboBox<>();
        cboChucVuTimKiem = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jpChucVu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLamMoiCV = new javax.swing.JButton();
        btnXoaCV = new javax.swing.JButton();
        btnSuaCV = new javax.swing.JButton();
        btnThemCV = new javax.swing.JButton();
        txtTenCV = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();

        setBackground(new java.awt.Color(207, 231, 255));
        setForeground(new java.awt.Color(13, 71, 161));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jTabbedPane1.setBackground(new java.awt.Color(207, 231, 255));
        jTabbedPane1.setForeground(new java.awt.Color(13, 71, 161));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jpNhanVien.setBackground(new java.awt.Color(207, 231, 255));
        jpNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(13, 71, 161))); // NOI18N
        jpNhanVien.setForeground(new java.awt.Color(13, 71, 161));

        lblMaNV.setForeground(new java.awt.Color(13, 71, 161));
        lblMaNV.setText("Mã NV");

        lblHoVaTen.setForeground(new java.awt.Color(13, 71, 161));
        lblHoVaTen.setText("Họ và Tên");

        lblNgaySinh.setForeground(new java.awt.Color(13, 71, 161));
        lblNgaySinh.setText("Ngày sinh");

        lblDiaChi.setForeground(new java.awt.Color(13, 71, 161));
        lblDiaChi.setText("Địa chỉ");

        txtHoVaTen.setPreferredSize(new java.awt.Dimension(0, 25));

        txtMaNV.setPreferredSize(new java.awt.Dimension(0, 25));

        txtEmail.setPreferredSize(new java.awt.Dimension(0, 25));

        txtSDT.setPreferredSize(new java.awt.Dimension(0, 25));

        lblSDT.setForeground(new java.awt.Color(13, 71, 161));
        lblSDT.setText("SDT");

        lblEmail.setForeground(new java.awt.Color(13, 71, 161));
        lblEmail.setText("Email");

        lblMatKhau.setForeground(new java.awt.Color(13, 71, 161));
        lblMatKhau.setText("Mật khẩu");

        lblChucVu.setForeground(new java.awt.Color(13, 71, 161));
        lblChucVu.setText("Chức vụ");

        lblAnhNV.setForeground(new java.awt.Color(255, 255, 255));
        lblAnhNV.setText("Ảnh NV");
        lblAnhNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnhNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhNVMouseClicked(evt);
            }
        });

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChucVu.setPreferredSize(new java.awt.Dimension(0, 25));

        lblGioiTinh.setForeground(new java.awt.Color(13, 71, 161));
        lblGioiTinh.setText("Giới tính");

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        btgSex.add(rdoNam);
        rdoNam.setForeground(new java.awt.Color(13, 71, 161));
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        btgSex.add(rdoNu);
        rdoNu.setForeground(new java.awt.Color(13, 71, 161));
        rdoNu.setText("Nữ");

        btgTrangThai.add(rdoNghiLam);
        rdoNghiLam.setForeground(new java.awt.Color(13, 71, 161));
        rdoNghiLam.setText("Nghỉ làm");

        btgTrangThai.add(rdoDiLam);
        rdoDiLam.setForeground(new java.awt.Color(13, 71, 161));
        rdoDiLam.setSelected(true);
        rdoDiLam.setText("Đi làm");

        lblTrangThai.setForeground(new java.awt.Color(13, 71, 161));
        lblTrangThai.setText("Trạng thái");

        txtNgaySinh.setDateFormatString("d/M/yyyy");
        txtNgaySinh.setPreferredSize(new java.awt.Dimension(0, 25));

        txtMatKhau.setText("123456");
        txtMatKhau.setFocusable(false);
        txtMatKhau.setPreferredSize(new java.awt.Dimension(0, 25));

        btnThem.setBackground(java.awt.Color.blue);
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Create.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setPreferredSize(new java.awt.Dimension(0, 35));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(java.awt.Color.blue);
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(0, 35));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(java.awt.Color.blue);
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(0, 35));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(java.awt.Color.blue);
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setPreferredSize(new java.awt.Dimension(0, 35));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(207, 231, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(13, 71, 161))); // NOI18N

        txtTimKiem.setForeground(new java.awt.Color(13, 71, 161));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        cboTimKiem.setForeground(new java.awt.Color(13, 71, 161));
        cboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Mã NV", "Họ và Tên", "SDT", "Email", "Chức Vụ" }));
        cboTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTimKiemActionPerformed(evt);
            }
        });

        cboChucVuTimKiem.setForeground(new java.awt.Color(13, 71, 161));
        cboChucVuTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChucVuTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChucVuTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboChucVuTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboChucVuTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblNhanVien.setBackground(new java.awt.Color(207, 231, 255));
        tblNhanVien.setForeground(new java.awt.Color(13, 71, 161));
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã NV", "Họ và Tên", "Giới tính", "Ngày sinh", "SDT", "Email", "Chức vụ", "Địa chỉ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblNhanVien.setRowHeight(25);
        tblNhanVien.getTableHeader().setResizingAllowed(false);
        tblNhanVien.getTableHeader().setReorderingAllowed(false);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jpNhanVienLayout = new javax.swing.GroupLayout(jpNhanVien);
        jpNhanVien.setLayout(jpNhanVienLayout);
        jpNhanVienLayout.setHorizontalGroup(
            jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNhanVienLayout.createSequentialGroup()
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHoVaTen)
                                            .addComponent(lblMaNV))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblGioiTinh)
                                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNgaySinh)
                                            .addComponent(lblDiaChi))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jpNhanVienLayout.createSequentialGroup()
                                                .addComponent(rdoNam)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdoNu))
                                            .addGroup(jpNhanVienLayout.createSequentialGroup()
                                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(33, 33, 33)))))
                                .addGap(81, 81, 81)
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTrangThai)
                                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpNhanVienLayout.createSequentialGroup()
                                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblMatKhau)
                                                    .addComponent(lblChucVu))
                                                .addGap(18, 18, 18)
                                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jpNhanVienLayout.createSequentialGroup()
                                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblEmail)
                                                    .addComponent(lblSDT))
                                                .addGap(39, 39, 39)
                                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(rdoDiLam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNghiLam))))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(196, 304, Short.MAX_VALUE))))
        );
        jpNhanVienLayout.setVerticalGroup(
            jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNhanVienLayout.createSequentialGroup()
                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNhanVienLayout.createSequentialGroup()
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpNhanVienLayout.createSequentialGroup()
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpNhanVienLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jpNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu)
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoDiLam)
                    .addComponent(rdoNghiLam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhân Viên", jpNhanVien);

        jPanel1.setBackground(new java.awt.Color(207, 231, 255));

        btnLamMoiCV.setBackground(new java.awt.Color(30, 136, 229));
        btnLamMoiCV.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoiCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnLamMoiCV.setText("Làm mới");
        btnLamMoiCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiCVActionPerformed(evt);
            }
        });

        btnXoaCV.setBackground(new java.awt.Color(30, 136, 229));
        btnXoaCV.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaCV.setText("Xóa");
        btnXoaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCVActionPerformed(evt);
            }
        });

        btnSuaCV.setBackground(new java.awt.Color(30, 136, 229));
        btnSuaCV.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSuaCV.setText("Sửa");
        btnSuaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCVActionPerformed(evt);
            }
        });

        btnThemCV.setBackground(new java.awt.Color(30, 136, 229));
        btnThemCV.setForeground(new java.awt.Color(255, 255, 255));
        btnThemCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Create.png"))); // NOI18N
        btnThemCV.setText("Thêm");
        btnThemCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCVActionPerformed(evt);
            }
        });

        txtID.setFocusable(false);

        lblID.setForeground(new java.awt.Color(13, 71, 161));
        lblID.setText("ID");

        lblEmail1.setForeground(new java.awt.Color(13, 71, 161));
        lblEmail1.setText("Tên chức vụ");

        tblChucVu.setBackground(new java.awt.Color(207, 231, 255));
        tblChucVu.setForeground(new java.awt.Color(13, 71, 161));
        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChucVu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblChucVu.setRowHeight(25);
        tblChucVu.getTableHeader().setResizingAllowed(false);
        tblChucVu.getTableHeader().setReorderingAllowed(false);
        tblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucVuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblChucVu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail1)
                            .addComponent(lblID))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLamMoiCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemCV, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 725, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemCV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoiCV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpChucVuLayout = new javax.swing.GroupLayout(jpChucVu);
        jpChucVu.setLayout(jpChucVuLayout);
        jpChucVuLayout.setHorizontalGroup(
            jpChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpChucVuLayout.setVerticalGroup(
            jpChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chức Vụ", jpChucVu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAnhNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhNVMouseClicked
        try {
            FileDialog fd = new FileDialog((Frame) null, "Chọn ảnh nhân viên", FileDialog.LOAD);
            fd.setDirectory("");
            fd.setFile("*.jpg;*.png");
            fd.setVisible(true);
            if (fd.getFile() != null) {
                File file = new File(fd.getDirectory(), fd.getFile());
                if (!file.getName().matches("(?i).+\\.(jpg|jpeg|png)$")) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn file ảnh (.jpg, .png)");
                    return;
                }
                Image img = ImageIO.read(file);
                fileAnh = file.getPath();
                int w = lblAnhNV.getWidth();
                int h = lblAnhNV.getHeight();
                lblAnhNV.setIcon(new ImageIcon(img.getScaledInstance(w, h, Image.SCALE_SMOOTH)));
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblAnhNVMouseClicked

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        this.edit();
    }//GEN-LAST:event_tblNhanVienMouseClicked

    public boolean isCheckNV() {
        System.out.println(fileAnh);
        if (txtHoVaTen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập tên nhân viên!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtHoVaTen.requestFocus();
            return true;
        } else if (txtNgaySinh.getDate() == null) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập ngày sinh!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtNgaySinh.requestFocus();
            return true;
        } else if (txtDiaChi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập địa chỉ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtDiaChi.requestFocus();
            return true;
        } else if (txtSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "vui lòng số điện thoại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtSDT.requestFocus();
            return true;
        } else if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng số email!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return true;
        } else if (!txtHoVaTen.getText().matches("[A-Za-zÀ-ỹ ]+")) {
            JOptionPane.showMessageDialog(this, "Tên nhân viên chỉ được chứa chữ cái!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtHoVaTen.requestFocus();
            return true;
        } else if (!txtSDT.getText().matches("^(0[3|5|7|8|9])[0-9]{8}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtSDT.requestFocus();
            return true;
        } else if (!txtEmail.getText().matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return true;
        } else if (txtNgaySinh.getDate().after(new Date())) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không được lớn hơn ngày hiện tại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtNgaySinh.requestFocus();
            return true;
        } else if (fileAnh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ảnh của nhân viên!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            this.lblAnhNVMouseClicked(null);
            
            return true;
        }
        return false;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (isCheckNV()) {
            return;
        }
        this.create();
        this.fillToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (isCheckNV()) {
            return;
        }
        this.update();
        this.fillToTable();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here
        if (tblNhanVien.getSelectedRow() >= 0) {
            this.delete();
            this.fillToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn xóa!", "Thông báo", JOptionPane.DEFAULT_OPTION);
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnLamMoiCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiCVActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtTenCV.setText("");
    }//GEN-LAST:event_btnLamMoiCVActionPerformed
    public boolean checkCV() {
        String ma = txtID.getText().trim();
        String ten = txtTenCV.getText().trim();

        if (ma.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã chức vụ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtID.requestFocus();
            return true;
        }

        if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên chức vụ!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtTenCV.requestFocus();
            return true;
        }

        if (!ma.matches("[A-Za-z0-9]+")) {
            JOptionPane.showMessageDialog(this, "Mã chức vụ chỉ được chứa chữ và số!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtID.requestFocus();
            return true;
        }

        if (!ten.matches("[A-Za-zÀ-ỹ ]+")) {
            JOptionPane.showMessageDialog(this, "Tên chức vụ chỉ được chứa chữ cái!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtTenCV.requestFocus();
            return true;
        }

        return false;
    }
    private void btnXoaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCVActionPerformed
        // TODO add your handling code here:
        if (tblChucVu.getSelectedRow() > 0) {
            repoCV.deleteByMaCV(tblChucVu.getValueAt(tblChucVu.getSelectedRow(), 1).toString());
            this.fillToTable();
            this.fillToComboBox();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaCVActionPerformed

    private void btnSuaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCVActionPerformed
        // TODO add your handling code here:
        if (checkCV()) {
            return;
        }
        repoCV.update(new ChucVu(Integer.parseInt(txtID.getText()), txtTenCV.getText()));
        this.fillToTable();
        this.fillToComboBox();
    }//GEN-LAST:event_btnSuaCVActionPerformed

    private void btnThemCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCVActionPerformed
        // TODO add your handling code here:
        if (checkCV()) {
            return;
        }
        repoCV.create(new ChucVu(Integer.parseInt(txtID.getText()), txtTenCV.getText()));
        this.fillToTable();
        this.fillToComboBox();
    }//GEN-LAST:event_btnThemCVActionPerformed

    private void tblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucVuMouseClicked
        // TODO add your handling code here:
        ChucVu chucvu = repoCV.findbyMaChucVu(tblChucVu.getValueAt(tblChucVu.getSelectedRow(), 1).toString());
        txtID.setText(String.valueOf(chucvu.getId()));
        txtTenCV.setText(chucvu.getTenChucVu());
    }//GEN-LAST:event_tblChucVuMouseClicked

    private void cboChucVuTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChucVuTimKiemActionPerformed
        // TODO add your handling code here:
        if (this.cboChucVuTimKiem.isVisible()) {
            modelNV = (DefaultTableModel) tblNhanVien.getModel();
            modelNV.setRowCount(0);
            for (NhanVien nhanVien : repoNV.findByToTable(cboChucVuTimKiem.getSelectedItem().toString(), cboTimKiem.getSelectedIndex())) {
                modelNV.addRow(new Object[]{nhanVien.getId(), nhanVien.getMaNhanVien(), nhanVien.getHoVaTen(),
                    nhanVien.isGioiTinh() ? "Nam" : "Nữ", nhanVien.getNgaySinh(), nhanVien.getsDT(),
                    nhanVien.getEmail(), nhanVien.getTenChucVu(), nhanVien.getDiaChi(), nhanVien.isTrangThai() ? "Đi làm" : "Nghỉ làm"});
            }
        }
    }//GEN-LAST:event_cboChucVuTimKiemActionPerformed

    private void cboTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTimKiemActionPerformed
        // TODO add your handling code here:
        if (cboTimKiem.getSelectedIndex() == 5) {
            txtTimKiem.setVisible(false);
            cboChucVuTimKiem.setVisible(true);
            this.cboChucVuTimKiemActionPerformed(null);
        } else {
            txtTimKiem.setVisible(true);
            cboChucVuTimKiem.setVisible(false);
            this.fillToTableFind();
        }
    }//GEN-LAST:event_cboTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        this.fillToTableFind();
    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSex;
    private javax.swing.ButtonGroup btgTrangThai;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiCV;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaCV;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemCV;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaCV;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboChucVuTimKiem;
    private javax.swing.JComboBox<String> cboTimKiem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpChucVu;
    private javax.swing.JPanel jpNhanVien;
    private javax.swing.JLabel lblAnhNV;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoVaTen;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JRadioButton rdoDiLam;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNghiLam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenCV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(NhanVien entity) {
        txtMaNV.setText(entity.getMaNhanVien());
        txtHoVaTen.setText(entity.getHoVaTen());
        txtNgaySinh.setDate(entity.getNgaySinh());
        txtDiaChi.setText(entity.getDiaChi());
        txtSDT.setText(entity.getsDT());
        txtEmail.setText(entity.getEmail());
        cboChucVu.setSelectedItem(entity.getTenChucVu());
        rdoNam.setSelected(entity.isGioiTinh());
        rdoNu.setSelected(!entity.isGioiTinh());
        rdoDiLam.setSelected(entity.isTrangThai());
        rdoNghiLam.setSelected(!entity.isTrangThai());
        ImageIcon icon = new ImageIcon(entity.getHinh());
        fileAnh = entity.getHinh();
        Image img = icon.getImage();
        lblAnhNV.setIcon(new ImageIcon(img.getScaledInstance(lblAnhNV.getWidth(), lblAnhNV.getHeight(), Image.SCALE_SMOOTH)));
    }

    @Override
    public NhanVien getForm() {
        int idCV = repoCV.findByName(cboChucVu.getSelectedItem().toString()).getId();
        return new NhanVien(txtMaNV.getText(), new String(txtMatKhau.getPassword()), txtHoVaTen.getText(), txtNgaySinh.getDate(), rdoNam.isSelected(), txtDiaChi.getText(), txtSDT.getText(), txtEmail.getText(), idCV, fileAnh, rdoDiLam.isSelected());
    }

    @Override
    public void fillToTable() {
        modelNV = (DefaultTableModel) tblNhanVien.getModel();
        modelNV.setRowCount(0);
        for (NhanVien nhanVien : repoNV.findAll()) {
            modelNV.addRow(new Object[]{nhanVien.getId(), nhanVien.getMaNhanVien(), nhanVien.getHoVaTen(),
                nhanVien.isGioiTinh() ? "Nam" : "Nữ", nhanVien.getNgaySinh(), nhanVien.getsDT(),
                nhanVien.getEmail(), nhanVien.getTenChucVu(), nhanVien.getDiaChi(), nhanVien.isTrangThai() ? "Đi làm" : "Nghỉ làm"});
        }
        modelCV = (DefaultTableModel) tblChucVu.getModel();
        modelCV.setRowCount(0);
        for (ChucVu chucVu : repoCV.findAll()) {
            modelCV.addRow(new Object[]{chucVu.getId(), chucVu.getTenChucVu()});
        }

    }

    @Override
    public void fillToTableFind() {
        modelNV = (DefaultTableModel) tblNhanVien.getModel();
        modelNV.setRowCount(0);
        for (NhanVien nhanVien : repoNV.findByToTable('%' + txtTimKiem.getText() + '%', cboTimKiem.getSelectedIndex())) {
            modelNV.addRow(new Object[]{nhanVien.getId(), nhanVien.getMaNhanVien(), nhanVien.getHoVaTen(),
                nhanVien.isGioiTinh() ? "Nam" : "Nữ", nhanVien.getNgaySinh(), nhanVien.getsDT(),
                nhanVien.getEmail(), nhanVien.getTenChucVu(), nhanVien.getDiaChi(), nhanVien.isTrangThai() ? "Đi làm" : "Nghỉ làm"});
        }
    }

    @Override
    public void fillToComboBox() {
        cboChucVu.removeAllItems();
        cboChucVuTimKiem.removeAllItems();
        for (ChucVu chucVu : repoCV.findAll()) {
            cboChucVu.addItem(chucVu.getTenChucVu());
            cboChucVuTimKiem.addItem(chucVu.getTenChucVu());
        }
    }

    @Override
    public void edit() {
        String manv = tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 1).toString();
        NhanVien nhanVien = repoNV.findByMaNV(manv);
        this.setForm(nhanVien);
    }

    @Override
    public void create() {;
        repoNV.create(this.getForm());
    }

    @Override
    public void update() {
        repoNV.update(this.getForm());
    }

    @Override
    public void delete() {
        repoNV.deleteByMaSV(tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 1).toString());
    }

    @Override
    public void clear() {
        txtMaNV.setText("");
        txtHoVaTen.setText("");
        txtNgaySinh.setDate(null);
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtEmail.setText("");
        cboChucVu.setSelectedItem("");
        btgSex.clearSelection();
        btgTrangThai.clearSelection();
        fileAnh = "";
        lblAnhNV.setIcon(null);
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
