/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import daoimpl.*;
import entity.*;
import entity.SanPham;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import controller.Controller_SanPham;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;

/**
 *
 * @author Administrator
 */
public class jpSanPham extends javax.swing.JPanel implements Controller_SanPham {

    /**
     * Creates new form jpSanPham
     */
    private DefaultTableModel modelSP = new DefaultTableModel();
    private DefaultTableModel modelNCC = new DefaultTableModel();
    private DefaultTableModel modelCT = new DefaultTableModel();
    private SanPham_Daoimpl repoSP = new SanPham_Daoimpl();
    private Mau_Daoimpl repoM = new Mau_Daoimpl();
    private KichCo_Daoimpl repoKC = new KichCo_Daoimpl();
    private LoaiGiay_Daoimpl repoL = new LoaiGiay_Daoimpl();
    private ChatLieu_Daoimpl repoCL = new ChatLieu_Daoimpl();
    private NhaCungCap_Daoimpl repoNCC = new NhaCungCap_Daoimpl();
    MouseAdapter hoverEffect = new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            JButton btn = (JButton) e.getSource();
            btn.setBackground(Color.DARK_GRAY);
        }

        @Override
        public void mouseExited(MouseEvent e) {
            JButton btn = (JButton) e.getSource();
            btn.setBackground(Color.BLUE);
        }
    };

    public jpSanPham() {
        initComponents();
        this.cboAllTimKiem.setVisible(false);
        this.fillToTable();
        this.fillToComboBox();
        btnLamMoi.addMouseListener(hoverEffect);
        btnLamMoi1.addMouseListener(hoverEffect);
        btnSua.addMouseListener(hoverEffect);
        btnThem.addMouseListener(hoverEffect);
        btnThemMau.addMouseListener(hoverEffect);
        btnXoa.addMouseListener(hoverEffect);
        btnXoaMau.addMouseListener(hoverEffect);
    }
    private String fileAnh;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTrangThai = new javax.swing.ButtonGroup();
        btgTrangThaiNCC = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpSanPham = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        lblAnhSP = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        cboTimKiem = new javax.swing.JComboBox<>();
        cboAllTimKiem = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        rdoConHang = new javax.swing.JRadioButton();
        rdoHetHang = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboMau = new javax.swing.JComboBox<>();
        cboKichCo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboChatLieu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboNhaCungCap = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jpChiTiet = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        txtSDTNCC = new javax.swing.JTextField();
        txtEmailNCC = new javax.swing.JTextField();
        txtIDNCC = new javax.swing.JTextField();
        rdoHoatDong = new javax.swing.JRadioButton();
        rdoDungHoatDong = new javax.swing.JRadioButton();
        btnLamMoi1 = new javax.swing.JButton();
        txtMauCT = new javax.swing.JTextField();
        txtChatLieuCT = new javax.swing.JTextField();
        txtLoaiCT = new javax.swing.JTextField();
        txtKichCoCT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnThemMau = new javax.swing.JButton();
        btnXoaMau = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDiaChiNCC = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(207, 231, 255));
        setForeground(new java.awt.Color(13, 71, 161));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new java.awt.CardLayout());

        jTabbedPane1.setBackground(new java.awt.Color(207, 231, 255));
        jTabbedPane1.setForeground(new java.awt.Color(13, 71, 161));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jTabbedPane1.setRequestFocusEnabled(false);

        jpSanPham.setBackground(new java.awt.Color(207, 231, 255));
        jpSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(13, 71, 161))); // NOI18N
        jpSanPham.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setForeground(new java.awt.Color(13, 71, 161));
        jLabel11.setText("Mô tả");
        jLabel11.setToolTipText("");
        jLabel11.setAlignmentY(1.0F);

        jScrollPane1.setForeground(new java.awt.Color(13, 71, 161));
        jScrollPane1.setToolTipText("");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setForeground(new java.awt.Color(13, 71, 161));
        jLabel12.setText("Trạng thái");
        jLabel12.setToolTipText("");
        jLabel12.setAlignmentY(1.0F);

        lblAnhSP.setForeground(new java.awt.Color(13, 71, 161));
        lblAnhSP.setText("Ảnh NV");
        lblAnhSP.setToolTipText("");
        lblAnhSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnhSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhSPMouseClicked(evt);
            }
        });

        btnThem.setBackground(java.awt.Color.blue);
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Create.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setToolTipText("");
        btnThem.setPreferredSize(new java.awt.Dimension(0, 35));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(java.awt.Color.blue);
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setToolTipText("");
        btnLamMoi.setPreferredSize(new java.awt.Dimension(0, 35));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setBackground(java.awt.Color.blue);
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setToolTipText("");
        btnXoa.setPreferredSize(new java.awt.Dimension(0, 35));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(java.awt.Color.blue);
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setToolTipText("");
        btnSua.setPreferredSize(new java.awt.Dimension(0, 35));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(207, 231, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(13, 71, 161))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(13, 71, 161));
        jPanel4.setToolTipText("");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        cboTimKiem.setForeground(new java.awt.Color(13, 71, 161));
        cboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tên SP", "Màu", "Kích cỡ", "Loại", "Chất liệu", "Nhà cung cấp" }));
        cboTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTimKiemActionPerformed(evt);
            }
        });

        cboAllTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAllTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboAllTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAllTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setForeground(new java.awt.Color(13, 71, 161));
        jScrollPane2.setToolTipText("");

        tblSanPham.setBackground(new java.awt.Color(207, 231, 255));
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên SP", "Giá nhập", "Giá bán", "Số lượng", "Màu", "Kích cỡ", "Loại", "Chất liệu", "Nhà cung cấp", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setRowHeight(25);
        tblSanPham.getTableHeader().setResizingAllowed(false);
        tblSanPham.getTableHeader().setReorderingAllowed(false);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        btgTrangThai.add(rdoConHang);
        rdoConHang.setText("Còn hàng");

        btgTrangThai.add(rdoHetHang);
        rdoHetHang.setText("Hết hàng");

        jLabel1.setText("ID");

        txtID.setFocusable(false);
        txtID.setPreferredSize(new java.awt.Dimension(71, 25));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtTenSP.setPreferredSize(new java.awt.Dimension(71, 25));

        jLabel2.setText("Tên");

        txtGiaNhap.setPreferredSize(new java.awt.Dimension(71, 25));

        jLabel3.setText("Giá nhập");

        txtGiaBan.setPreferredSize(new java.awt.Dimension(71, 25));

        jLabel4.setText("Giá bán");

        txtSoLuong.setPreferredSize(new java.awt.Dimension(71, 25));

        jLabel5.setText("Số lượng");

        jLabel6.setText("Màu");
        jLabel6.setToolTipText("");

        cboMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMau.setPreferredSize(new java.awt.Dimension(150, 25));

        cboKichCo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKichCo.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel7.setText("Kích cỡ");

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoai.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel8.setText("Loại");

        cboChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChatLieu.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel9.setText("Chất liệu");

        cboNhaCungCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNhaCungCap.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel10.setText("Nhà CC");

        javax.swing.GroupLayout jpSanPhamLayout = new javax.swing.GroupLayout(jpSanPham);
        jpSanPham.setLayout(jpSanPhamLayout);
        jpSanPhamLayout.setHorizontalGroup(
            jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSanPhamLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSanPhamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(rdoConHang)
                        .addGap(6, 6, 6)
                        .addComponent(rdoHetHang)))
                .addGap(6, 6, 6)
                .addComponent(lblAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jpSanPhamLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpSanPhamLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpSanPhamLayout.setVerticalGroup(
            jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSanPhamLayout.createSequentialGroup()
                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cboNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpSanPhamLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jpSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoConHang)
                                    .addComponent(rdoHetHang)))))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpSanPhamLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Sản Phẩm", jpSanPham);

        jpChiTiet.setBackground(new java.awt.Color(207, 231, 255));
        jpChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(13, 71, 161))); // NOI18N
        jpChiTiet.setForeground(new java.awt.Color(13, 71, 161));

        jScrollPane3.setForeground(new java.awt.Color(13, 71, 161));

        tblNCC.setBackground(new java.awt.Color(207, 231, 255));
        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "Địa chỉ", "SDT", "Email", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNCC.setRowHeight(25);
        tblNCC.getTableHeader().setResizingAllowed(false);
        tblNCC.getTableHeader().setReorderingAllowed(false);
        tblNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNCCMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNCC);

        jScrollPane4.setForeground(new java.awt.Color(13, 71, 161));

        tblChiTiet.setAutoCreateRowSorter(true);
        tblChiTiet.setBackground(new java.awt.Color(207, 231, 255));
        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Màu", "Kích cỡ", "Loại", "Chất liệu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTiet.setRowHeight(25);
        tblChiTiet.getTableHeader().setResizingAllowed(false);
        tblChiTiet.getTableHeader().setReorderingAllowed(false);
        tblChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblChiTiet);

        jLabel13.setForeground(new java.awt.Color(13, 71, 161));
        jLabel13.setText("ID");
        jLabel13.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel14.setForeground(new java.awt.Color(13, 71, 161));
        jLabel14.setText("Tên NCC");
        jLabel14.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel15.setForeground(new java.awt.Color(13, 71, 161));
        jLabel15.setText("Địa chỉ");
        jLabel15.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel16.setForeground(new java.awt.Color(13, 71, 161));
        jLabel16.setText("SDT");
        jLabel16.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel17.setForeground(new java.awt.Color(13, 71, 161));
        jLabel17.setText("Email");
        jLabel17.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel18.setForeground(new java.awt.Color(13, 71, 161));
        jLabel18.setText("Trạng thái");
        jLabel18.setPreferredSize(new java.awt.Dimension(43, 25));

        txtTenNCC.setPreferredSize(new java.awt.Dimension(200, 25));

        txtSDTNCC.setPreferredSize(new java.awt.Dimension(200, 25));

        txtEmailNCC.setPreferredSize(new java.awt.Dimension(200, 25));

        txtIDNCC.setFocusable(false);
        txtIDNCC.setPreferredSize(new java.awt.Dimension(200, 25));

        btgTrangThaiNCC.add(rdoHoatDong);
        rdoHoatDong.setForeground(new java.awt.Color(13, 71, 161));
        rdoHoatDong.setText("Hoạt động");

        btgTrangThaiNCC.add(rdoDungHoatDong);
        rdoDungHoatDong.setForeground(new java.awt.Color(13, 71, 161));
        rdoDungHoatDong.setText("Dừng hoạt dộng");

        btnLamMoi1.setBackground(java.awt.Color.blue);
        btnLamMoi1.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnLamMoi1.setText("Làm mới");
        btnLamMoi1.setPreferredSize(new java.awt.Dimension(100, 35));
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });

        txtMauCT.setPreferredSize(new java.awt.Dimension(200, 25));

        txtChatLieuCT.setPreferredSize(new java.awt.Dimension(200, 25));

        txtLoaiCT.setPreferredSize(new java.awt.Dimension(200, 25));

        txtKichCoCT.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel19.setForeground(new java.awt.Color(13, 71, 161));
        jLabel19.setText("Chất liệu");
        jLabel19.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel20.setForeground(new java.awt.Color(13, 71, 161));
        jLabel20.setText("Loại");
        jLabel20.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel21.setForeground(new java.awt.Color(13, 71, 161));
        jLabel21.setText("Kích cỡ");
        jLabel21.setPreferredSize(new java.awt.Dimension(43, 25));

        jLabel22.setForeground(new java.awt.Color(13, 71, 161));
        jLabel22.setText("Màu");
        jLabel22.setPreferredSize(new java.awt.Dimension(43, 25));

        btnThemMau.setBackground(java.awt.Color.blue);
        btnThemMau.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Create.png"))); // NOI18N
        btnThemMau.setText("Thêm");
        btnThemMau.setFocusable(false);
        btnThemMau.setPreferredSize(new java.awt.Dimension(100, 35));
        btnThemMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMauActionPerformed(evt);
            }
        });

        btnXoaMau.setBackground(java.awt.Color.blue);
        btnXoaMau.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaMau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaMau.setText("Xóa");
        btnXoaMau.setPreferredSize(new java.awt.Dimension(100, 35));
        btnXoaMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMauActionPerformed(evt);
            }
        });

        jScrollPane5.setForeground(new java.awt.Color(13, 71, 161));

        txtDiaChiNCC.setColumns(20);
        txtDiaChiNCC.setRows(5);
        jScrollPane5.setViewportView(txtDiaChiNCC);

        javax.swing.GroupLayout jpChiTietLayout = new javax.swing.GroupLayout(jpChiTiet);
        jpChiTiet.setLayout(jpChiTietLayout);
        jpChiTietLayout.setHorizontalGroup(
            jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpChiTietLayout.createSequentialGroup()
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpChiTietLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoHoatDong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoDungHoatDong))
                            .addGroup(jpChiTietLayout.createSequentialGroup()
                                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(141, 141, 141)
                                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChatLieuCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMauCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKichCoCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoaiCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLamMoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnXoaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(362, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpChiTietLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jpChiTietLayout.setVerticalGroup(
            jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChiTietLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpChiTietLayout.createSequentialGroup()
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpChiTietLayout.createSequentialGroup()
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMauCT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKichCoCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoaiCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChatLieuCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpChiTietLayout.createSequentialGroup()
                        .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoHoatDong)
                    .addComponent(rdoDungHoatDong))
                .addGap(18, 18, 18)
                .addGroup(jpChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chi Tiết", jpChiTiet);

        add(jTabbedPane1, "card2");

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void cboAllTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAllTimKiemActionPerformed
        // TODO add your handling code here:
        if ((this.cboAllTimKiem.getSelectedItem() != null) && this.cboAllTimKiem.isVisible()) {
            modelSP = (DefaultTableModel) tblSanPham.getModel();
            modelSP.setRowCount(0);
            System.out.println(cboAllTimKiem.getSelectedItem().toString() + ":" + cboTimKiem.getSelectedIndex());
            for (SanPham sanPham : repoSP.findByToTable(cboAllTimKiem.getSelectedItem().toString(), cboTimKiem.getSelectedIndex())) {
                modelSP.addRow(new Object[]{sanPham.getId(), sanPham.getTenGiay(), sanPham.getGiaNhap(), sanPham.getDonGia(), sanPham.getSoLuong(), sanPham.getTenMau(), sanPham.getTenKichCo(),
                    sanPham.getTenLoai(), sanPham.getTenChatLieu(), sanPham.getTenNCC(), sanPham.isTrangThai() ? "Còn hàng" : "Hết hàng"});
            }
        }
    }//GEN-LAST:event_cboAllTimKiemActionPerformed

    private void cboTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTimKiemActionPerformed
        // TODO add your handling code here:
        int index = cboTimKiem.getSelectedIndex();
        cboAllTimKiem.removeAllItems();
        txtTimKiem.setVisible(false);

        switch (index) {
            case 2:
                for (Mau mau : repoM.findAll()) {
                    cboAllTimKiem.addItem(mau.getTenMau());
                }
                cboAllTimKiem.setVisible(true);
                if (cboAllTimKiem.getItemCount() > 0) {
                    cboAllTimKiem.setSelectedIndex(0);
                }
                break;
            case 3:
                for (KichCo kichCo : repoKC.findAll()) {
                    cboAllTimKiem.addItem(kichCo.getTenKichCo());
                }
                cboAllTimKiem.setVisible(true);
                if (cboAllTimKiem.getItemCount() > 0) {
                    cboAllTimKiem.setSelectedIndex(0);
                }
                break;
            case 4:
                for (LoaiGiay loai : repoL.findAll()) {
                    cboAllTimKiem.addItem(loai.getTenLoai());
                }
                cboAllTimKiem.setVisible(true);
                if (cboAllTimKiem.getItemCount() > 0) {
                    cboAllTimKiem.setSelectedIndex(0);
                }
                break;
            case 5:
                for (ChatLieu chatLieu : repoCL.findAll()) {
                    cboAllTimKiem.addItem(chatLieu.getTenChatLieu());
                }
                cboAllTimKiem.setVisible(true);
                if (cboAllTimKiem.getItemCount() > 0) {
                    cboAllTimKiem.setSelectedIndex(0);
                }
                break;
            case 6:
                for (NhaCungCap nhaCungCap : repoNCC.findAll()) {
                    cboAllTimKiem.addItem(nhaCungCap.getTenNCC());
                }
                cboAllTimKiem.setVisible(true);
                if (cboAllTimKiem.getItemCount() > 0) {
                    cboAllTimKiem.setSelectedIndex(0);
                }
                break;
            default:
                txtTimKiem.setVisible(true);
                cboAllTimKiem.setVisible(false);
                break;
        }
    }//GEN-LAST:event_cboTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        this.fillToTableFind();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
        this.fillToTable();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here
        if (tblSanPham.getSelectedRow() >= 0) {
            this.delete();
            this.fillToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn xóa!", "Thông báo", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.create();
        this.fillToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void lblAnhSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhSPMouseClicked
        try {
            FileDialog fd = new FileDialog((Frame) null, "Chọn ảnh nhân viên", FileDialog.LOAD);
            fd.setDirectory("");
            fd.setFile("*.jpg;*.png");
            fd.setVisible(true);
            if (fd.getFile() != null) {
                File file = new File(fd.getDirectory(), fd.getFile());
                if (!file.getName().matches("(?i).+\\.(jpg|jpeg|png)$")) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn file ảnh (.jpg, .png)");
                    return;
                }
                Image img = ImageIO.read(file);
                fileAnh = file.getPath();
                int w = lblAnhSP.getWidth();
                int h = lblAnhSP.getHeight();
                lblAnhSP.setIcon(new ImageIcon(img.getScaledInstance(w, h, Image.SCALE_SMOOTH)));
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblAnhSPMouseClicked

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void btnThemMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMauActionPerformed
        // TODO add your handling code here:
        if (txtMauCT.isFocusOwner()) {
            Mau mau = new Mau(txtMauCT.getText());
            repoM.create(mau);
            this.fillToTable();
        } else if (txtKichCoCT.isFocusOwner()) {
            KichCo kichCo = new KichCo(txtKichCoCT.getText());
            repoKC.create(kichCo);
            this.fillToTable();
        } else if (txtLoaiCT.isFocusOwner()) {
            LoaiGiay loaiGiay = new LoaiGiay(txtLoaiCT.getText());
            repoL.create(loaiGiay);
            this.fillToTable();
        } else if (txtChatLieuCT.isFocusOwner()) {
            ChatLieu chatLieu = new ChatLieu(txtChatLieuCT.getText());
            repoCL.create(chatLieu);
            this.fillToTable();
        } else if (txtTenNCC.isFocusOwner() || txtDiaChiNCC.isFocusOwner() || txtEmailNCC.isFocusOwner() || txtSDTNCC.isFocusOwner() || rdoHoatDong.isSelected() || rdoDungHoatDong.isSelected()) {
            NhaCungCap nhaCungCap = new NhaCungCap(txtTenNCC.getText(), txtDiaChiNCC.getText(), txtSDTNCC.getText(), txtEmailNCC.getText(), rdoHoatDong.isSelected());
            repoNCC.create(nhaCungCap);
            this.fillToTable();
        }
        fillToComboBox();
        clear();
    }//GEN-LAST:event_btnThemMauActionPerformed

    private void btnXoaMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMauActionPerformed
        // TODO add your handling code here:
        if (tblNCC.getSelectedRow() < 0 && tblChiTiet.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tblChiTiet.getSelectedColumn() == 0 && tblChiTiet.getSelectedRow() > -1) {
            repoM.deleteByName(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), 0).toString());
            this.fillToTable();
        } else if (tblChiTiet.getSelectedColumn() == 1 && tblChiTiet.getSelectedRow() > -1) {
            repoKC.deleteByName(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), 1).toString());
            this.fillToTable();
        } else if (tblChiTiet.getSelectedColumn() == 2 && tblChiTiet.getSelectedRow() > -1) {
            repoL.deleteByName(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), 2).toString());
            this.fillToTable();
        } else if (tblChiTiet.getSelectedColumn() == 3 && tblChiTiet.getSelectedRow() > -1) {
            repoCL.deleteByName(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), 3).toString());
            this.fillToTable();
        } else if (tblNCC.getSelectedRow() > - 1) {
            repoNCC.deleteById(Integer.parseInt(txtIDNCC.getText()));
            this.fillToTable();
        }
        fillToComboBox();
        clear();
    }//GEN-LAST:event_btnXoaMauActionPerformed

    private void tblChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietMouseClicked
        // TODO add your handling code here:
        if (tblChiTiet.getSelectedColumn() == 0 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) != null) {
            txtMauCT.setText(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()).toString());
        } else if (tblChiTiet.getSelectedColumn() == 0 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) == null) {
            txtMauCT.setText(null);
        }
        if (tblChiTiet.getSelectedColumn() == 1 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) != null) {
            txtKichCoCT.setText(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()).toString());
        } else if (tblChiTiet.getSelectedColumn() == 1 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) == null) {
            txtKichCoCT.setText(null);
        }
        if (tblChiTiet.getSelectedColumn() == 2 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) != null) {
            txtLoaiCT.setText(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()).toString());
        } else if (tblChiTiet.getSelectedColumn() == 2 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) == null) {
            txtLoaiCT.setText(null);
        }
        if (tblChiTiet.getSelectedColumn() == 3 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) != null) {
            txtChatLieuCT.setText(tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()).toString());
        } else if (tblChiTiet.getSelectedColumn() == 3 && tblChiTiet.getValueAt(tblChiTiet.getSelectedRow(), tblChiTiet.getSelectedColumn()) == null) {
            txtChatLieuCT.setText(null);
        }
    }//GEN-LAST:event_tblChiTietMouseClicked

    private void tblNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNCCMouseClicked
        // TODO add your handling code here:
        NhaCungCap nhaCungCap = repoNCC.findById(Integer.parseInt(tblNCC.getValueAt(tblNCC.getSelectedRow(), 0).toString()));
        txtIDNCC.setText(String.valueOf(nhaCungCap.getId()));
        txtTenNCC.setText(nhaCungCap.getTenNCC());
        txtSDTNCC.setText(nhaCungCap.getsDT());
        txtEmailNCC.setText(nhaCungCap.getEmail());
        txtDiaChiNCC.setText(nhaCungCap.getDiaChi());
        rdoHoatDong.setSelected(nhaCungCap.isTrangThai());
        rdoDungHoatDong.setSelected(!nhaCungCap.isTrangThai());
    }//GEN-LAST:event_tblNCCMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        this.edit();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTrangThai;
    private javax.swing.ButtonGroup btgTrangThaiNCC;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoi1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemMau;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaMau;
    private javax.swing.JComboBox<String> cboAllTimKiem;
    private javax.swing.JComboBox<String> cboChatLieu;
    private javax.swing.JComboBox<String> cboKichCo;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JComboBox<String> cboNhaCungCap;
    private javax.swing.JComboBox<String> cboTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpChiTiet;
    private javax.swing.JPanel jpSanPham;
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JRadioButton rdoConHang;
    private javax.swing.JRadioButton rdoDungHoatDong;
    private javax.swing.JRadioButton rdoHetHang;
    private javax.swing.JRadioButton rdoHoatDong;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtChatLieuCT;
    private javax.swing.JTextArea txtDiaChiNCC;
    private javax.swing.JTextField txtEmailNCC;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDNCC;
    private javax.swing.JTextField txtKichCoCT;
    private javax.swing.JTextField txtLoaiCT;
    private javax.swing.JTextField txtMauCT;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSDTNCC;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(SanPham entity) {
        txtID.setText(String.valueOf(entity.getId()));
        txtTenSP.setText(entity.getTenGiay());
        txtGiaNhap.setText(entity.getGiaNhap().stripTrailingZeros().toPlainString());
        txtGiaBan.setText(entity.getDonGia().stripTrailingZeros().toPlainString());

        txtSoLuong.setText(String.valueOf(entity.getSoLuong()));
        txtMoTa.setText(entity.getMoTa());
        cboMau.setSelectedItem(entity.getTenMau());
        cboKichCo.setSelectedItem(entity.getTenKichCo());
        cboLoai.setSelectedItem(entity.getTenLoai());
        cboChatLieu.setSelectedItem(entity.getTenChatLieu());
        cboNhaCungCap.setSelectedItem(entity.getTenNCC());
        rdoConHang.setSelected(entity.isTrangThai());
        rdoHetHang.setSelected(!entity.isTrangThai());
        ImageIcon icon = new ImageIcon(entity.getHinh());
        fileAnh = entity.getHinh();
        Image img = icon.getImage();
        lblAnhSP.setIcon(new ImageIcon(img.getScaledInstance(lblAnhSP.getWidth(), lblAnhSP.getHeight(), Image.SCALE_SMOOTH)));
    }

    @Override
    public SanPham getForm() {

        int idMau = repoM.findByName(cboMau.getSelectedItem().toString()).getId();
        int size = repoKC.findByName(cboKichCo.getSelectedItem().toString()).getId();
        int idLoaiGiay = repoL.findByName(cboLoai.getSelectedItem().toString()).getId();
        int idchatLieu = repoCL.findByName(cboChatLieu.getSelectedItem().toString()).getId();
        int idNhaCungCap = repoNCC.findByName(cboNhaCungCap.getSelectedItem().toString()).getId();
        return new SanPham(txtTenSP.getText(), new BigDecimal(txtGiaNhap.getText()), new BigDecimal(txtGiaBan.getText()), Integer.parseInt(txtSoLuong.getText()),
                idMau, size, idLoaiGiay, idchatLieu, fileAnh, rdoConHang.isSelected(), txtMoTa.getText(), idNhaCungCap);
    }

    public SanPham getFormUpdate() {

        int idMau = repoM.findByName(cboMau.getSelectedItem().toString()).getId();
        int size = repoKC.findByName(cboKichCo.getSelectedItem().toString()).getId();
        int idLoaiGiay = repoL.findByName(cboLoai.getSelectedItem().toString()).getId();
        int idchatLieu = repoCL.findByName(cboChatLieu.getSelectedItem().toString()).getId();
        int idNhaCungCap = repoNCC.findByName(cboNhaCungCap.getSelectedItem().toString()).getId();
        return new SanPham(Integer.parseInt(txtID.getText()), txtTenSP.getText(), new BigDecimal(txtGiaNhap.getText()), new BigDecimal(txtGiaBan.getText()), Integer.parseInt(txtSoLuong.getText()),
                idMau, size, idLoaiGiay, idchatLieu, fileAnh, rdoConHang.isSelected(), txtMoTa.getText(), idNhaCungCap);
    }

    @Override
    public void fillToTable() {
        modelSP = (DefaultTableModel) tblSanPham.getModel();
        modelSP.setRowCount(0);
        for (SanPham sanPham : repoSP.findAll()) {
            modelSP.addRow(new Object[]{sanPham.getId(), sanPham.getTenGiay(), this.formatMoney(sanPham.getGiaNhap()), this.formatMoney(sanPham.getDonGia()), sanPham.getSoLuong(), sanPham.getTenMau(), sanPham.getTenKichCo(),
                sanPham.getTenLoai(), sanPham.getTenChatLieu(), sanPham.getTenNCC(), sanPham.isTrangThai() ? "Còn hàng" : "Hết hàng"});
        }
        modelCT = (DefaultTableModel) tblChiTiet.getModel();
        modelCT.setRowCount(0);
        int max = Math.max(
                Math.max(repoM.findAll().size(), repoKC.findAll().size()),
                Math.max(repoCL.findAll().size(), repoCL.findAll().size())
        );
        for (int i = 0; i < max; i++) {
            modelCT.addRow(new Object[]{null, null, null, null});
        }
        for (int i = 0; i < repoM.findAll().size(); i++) {
            modelCT.setValueAt(repoM.findAll().get(i).getTenMau(), i, 0);
        }
        for (int i = 0; i < repoKC.findAll().size(); i++) {
            modelCT.setValueAt(repoKC.findAll().get(i).getTenKichCo(), i, 1);
        }
        for (int i = 0; i < repoL.findAll().size(); i++) {
            modelCT.setValueAt(repoL.findAll().get(i).getTenLoai(), i, 2);
        }
        for (int i = 0; i < repoCL.findAll().size(); i++) {
            modelCT.setValueAt(repoCL.findAll().get(i).getTenChatLieu(), i, 3);
        }
        modelNCC = (DefaultTableModel) tblNCC.getModel();
        modelNCC.setRowCount(0);
        for (NhaCungCap nhaCungCap : repoNCC.findAll()) {
            modelNCC.addRow(new Object[]{nhaCungCap.getId(), nhaCungCap.getTenNCC(), nhaCungCap.getDiaChi(), nhaCungCap.getsDT(), nhaCungCap.getEmail(), nhaCungCap.isTrangThai() ? "Hoạt động" : "Dừng hoạt động"});
        }
    }

    private String formatMoney(BigDecimal money) {
        if (money == null) {
            return "";
        }
        DecimalFormat df = new DecimalFormat("#,### VNĐ");
        return df.format(money);
    }

    @Override
    public void fillToTableFind() {
        modelSP = (DefaultTableModel) tblSanPham.getModel();
        modelSP.setRowCount(0);
        for (SanPham sanPham : repoSP.findByToTable('%' + txtTimKiem.getText() + '%', cboTimKiem.getSelectedIndex())) {
            modelSP.addRow(new Object[]{sanPham.getId(), sanPham.getTenGiay(), sanPham.getGiaNhap(), sanPham.getDonGia(), sanPham.getSoLuong(), sanPham.getTenMau(), sanPham.getTenKichCo(),
                sanPham.getTenLoai(), sanPham.getTenChatLieu(), sanPham.getTenNCC(), sanPham.isTrangThai() ? "Còn hàng" : "Hết hàng"});
        }
    }

    @Override
    public void fillToComboBox() {
        cboMau.removeAllItems();
        cboKichCo.removeAllItems();
        cboLoai.removeAllItems();
        cboChatLieu.removeAllItems();
        cboNhaCungCap.removeAllItems();
        for (Mau mau : repoM.findAll()) {
            cboMau.addItem(mau.getTenMau());
        }
        for (KichCo kichCo : repoKC.findAll()) {
            cboKichCo.addItem(kichCo.getTenKichCo());
        }
        for (LoaiGiay loai : repoL.findAll()) {
            cboLoai.addItem(loai.getTenLoai());
        }
        for (ChatLieu chatLieu : repoCL.findAll()) {
            cboChatLieu.addItem(chatLieu.getTenChatLieu());
        }
        for (NhaCungCap nhaCungCap : repoNCC.findAll()) {
            cboNhaCungCap.addItem(nhaCungCap.getTenNCC());
        }
    }

    @Override
    public void edit() {
        int id = Integer.parseInt(tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 0).toString());
        SanPham sanPham = repoSP.findById(id);
        this.setForm(sanPham);
    }

    @Override
    public void create() {
        SanPham sanPham = this.getForm();
        repoSP.create(sanPham);
    }

    @Override
    public void update() {
        if (txtID.getText().length() < 0) {
            JOptionPane.showMessageDialog(this, "ID không được để trống!", "Thông báo!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        SanPham sanPham = this.getFormUpdate();
        repoSP.update(sanPham);
    }

    @Override
    public void delete() {
        if (tblSanPham.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng muốn xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        repoSP.deleteById(Integer.parseInt(tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 0).toString()));
    }

    @Override
    public void clear() {
        txtID.setText("");
        txtTenSP.setText("");
        txtGiaNhap.setText("");
        txtGiaBan.setText("");
        txtSoLuong.setText("");
        txtMoTa.setText("");
        cboMau.setSelectedIndex(-1);
        cboKichCo.setSelectedIndex(-1);
        cboLoai.setSelectedIndex(-1);
        cboChatLieu.setSelectedIndex(-1);
        cboNhaCungCap.setSelectedIndex(-1);
        btgTrangThai.clearSelection();
        lblAnhSP.setIcon(null);
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
